### ISSUE TITLE
I couldn't login using default account

### ISSUE THREAD

**Issue by hayleyshim** [rexeze/React-Chat-App-with-CometChat#1]
I changed 'API_ID, API_KEY'  in setting.js.

So, I can access to the main page.

But, when I input default account such as superhero1,superhero2 etc. , I saw the error message 'Login failed, please enter a valid username' .

How can I login with my account?

**Comment by bookercodes** [comment]
Oh, no. Looking at [the code](https://github.com/cometchat-pro-tutorials/slack-clone/blob/master/src/components/Login/index.js#L48), I see we show the message "Login failed, please enter a valid username" when **any** error happens. You will see a more specific error in the console. Would you please share it?

**Comment by hayleyshim** [comment]
Thank you for your response!^^

<img width="264" alt="login" src="https://user-images.githubusercontent.com/8789789/66620262-ca5e6700-ec1a-11e9-8595-93b5b3fda5ec.PNG">


this is my login page ㅜ.ㅜ

and there is nothing to see in the console.

<img width="253" alt="console" src="https://user-images.githubusercontent.com/8789789/66620293-e3ffae80-ec1a-11e9-9b89-733cb1a5ca2f.PNG">


I think it's not optimized for my web page?!

So, I have already found another cometchat_source which can be compiled.

Anyway, thank you for your fast response!

Have a nice day!!!

From Yonghui Shim.

2019년 10월 6일 (일) 오전 9:10, Alex Booker <notifications@github.com>님이 작성:

**Comment by bookercodes** [comment]
Fantastic. If you need any help with CometChat, feel free to join our [Slack channel](https://slack.cometchat.com/)!
